name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        go-version: [1.21.x, 1.22.x, 1.23.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: go vet
        run: go vet ./...
      - name: go test
        run: go test -v ./...
